#!/bin/bash
echo "Enter the message to be encrypted:"
read message
echo "Enter the shift value:"
read shift
encrypted=$(echo $message | tr "A-Za-z" "$(echo {A..Z} | tr -d ' ')$(echo {a..z} | tr -d ' ')" | tr "$(echo {a..z} | tr -d ' ')" "$(echo {a..z} | tr -d ' '| cut -c$((shift+1))-$(echo {a..z} |tr-d '' | wc -c))$(echo {a..z} | tr -d ' ' | cut -c1-$shift)")
echo "The encrypted message is: $encrypted"
